import type { Portfolio } from "./types"

export const portfolioData: Portfolio[] = [
  {
    id: "1",
    name: "Thagul Nantasuwan",
    photo: "/photos/thagul-nantasuwan.jpg",
    description: "Computer Engineer passionate about scalable software and AI solutions. Focused on clean code, performance, and solving real-world problems with intelligent algorithms.",
    portfolioUrl: "/portfolios/thagul-nantasuwan.pdf",
    programme: "CET1",
    major: "Computer Engineer",
    university: "Chulalongkorn University",
    universitySeal: "/seals/cu.png",
    instagram: "https://instagram.com/gao_thagul",
    facebook: "https://facebook.com/thagul.nantasuwan",
    github: "https://github.com/thagul2550",
  },
  {
    id: "2",
    name: "Korawit Kaewkong",
    photo: "/photos/korawit-kaewkong.jpg",
    description: "NewType Otaku, 6000hrs+ on anime, Jack of all trades ,gambling addict(hsr)",
    portfolioUrl: "/portfolios/korawit-kaewkong.pdf",
    programme: "CET1",
    major: "Computer Science",
    university: "Chulalongkorn University",
    universitySeal: "/seals/cu.png",
    instagram: "https://www.instagram.com/gusgoodsman/",
    facebook: "https://www.facebook.com/focus.focus.1466/",
    github: "https://github.com/Tazeon",
  },
  {
    id: "3",
    name: "Tanat Samuttha",
    photo: "/photos/tanat-samuttha.jpg",
    description: "Success isn’t random — it’s the result of optimal pathfinding.",
    portfolioUrl: "/portfolios/tanat-samuttha.pdf",
    programme: "CET1",
    major: "Computer Engineer",
    university: "Chulalongkorn University",
    universitySeal: "/seals/cu.png",
    instagram: "https://instagram.com/nine.nsm",
    facebook: "https://facebook.com/thnath.smuththa",
    github: "https://github.com/TanatSamuttha",
  },
  {
    id: "4",
    name: "Siri Khanansuk",
    photo: "/photos/siri-khanansuk.jpg",
    description: "Tryharder, 150 hrs+ on Elden ring with all achievements , Gambling addicted, Sold my soul to english, love going gym",
    portfolioUrl: "/portfolios/siri-khanansuk.pdf",
    programme: "CET1",
    major: "IoT Engineer",
    university: "King Mongkut's Ladkrabang",
    universitySeal: "/seals/kmitl.png",
    instagram: "https://instagram.com/arc_archay",
    facebook: "https://facebook.com/archay24",
    github: "https://github.com/arcdoesntexist",
  }
]

// {
//   id: "PASS",
//   name: "Kittitouch Thipmontha",
//   photo: "PASS",
//   description: "Your quote or interests",
//   portfolioUrl: "PASS",
//   major: "Computer Engineer",
//   university: "Chulalongkorn University",
//   universitySeal: "PASS",
//   instagram: "https://instagram.com/Nonbangkok",
//   facebook: "https://facebook.com/Nonbangkok",
//   github: "https://github.com/Nonbangkok",
// }